import type { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";
import { HeaderComponent } from "@/app/components/header.component";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main className="container mx-auto">
            <HeaderComponent></HeaderComponent>

            <div className="flex z-40 w-full h-auto items-center justify-center">
              <div className="mt-12 px-6 w-full max-w-[1024px]">{children}</div>
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
